### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by VoyTechnology**
This enables the application to be ran inside a container.
Also contained in this change:
* Small styling changes
* Change to bind to `0.0.0.0`.

### CODE REVIEW

**Comment by CianLR** [comment]
V nice. I'll wait for Noah's input on the bind address change, I'm not sure how his DigitalOcean is setup, exposing 4321 may cause issues for him. (He'll be awake soon)

**Comment by VoyTechnology** [comment]
Yes, that might be a potential security hazard. But with docker you still need to use `-p <EXTERNAL>:4321`. When it comes to externally exposing the application on the running node, simple firewall should be better (only allowing HTTP and SSH).

Another option would be to expose the host address as `bind` flag, that way it would be possible in the docker container to set `--bind=0.0.0.0` to achieve the same goal and leave `127.0.0.1` as the default.

**Comment by CianLR** [comment]
The command line param sounds like a good way to go, I've been meaning to pull out some of the constants in a similar manner anyhow.
Could you use argparse to do it?

**Comment by iandioch** [comment]
Not sure on the need for a dockerfile when we aren't using docker, but can't do harm. 

I have no issues re: 0.0.0.0

:approve:

**Comment by iandioch** [comment]
Thanks for the additions by the way @VoyTechnology, the new search bar looks superb.

**Pull request merged**
